CREATE TABLE CATEGORIA(
	IDCATEGORIA INT NOT NULL,
	DESCRICAO VARCHAR(20) NOT NULL,
	DIARIA NUMERIC(7,2) NOT NULL,
	PRIMARY KEY (IDCATEGORIA)	
);

CREATE TABLE MODELO(
	IDMODELO INT NOT NULL,
	SIGLA CHAR(5),
	IDCATEGORIA INT NOT NULL,
	PRIMARY KEY(IDMODELO),
	FOREIGN KEY(IDCATEGORIA) REFERENCES CATEGORIA(IDCATEGORIA)
);
CREATE TABLE AUTOMOVEL(
	PLACA CHAR(7) NOT NULL,
	DESCRICAO VARCHAR(30),
	COR VARCHAR(15),
	IDMODELO INT NOT NULL,
	PRIMARY KEY (PLACA),
	FOREIGN KEY(IDMODELO) REFERENCES MODELO(IDMODELO)
);

CREATE TABLE CLIENTE(
	CPF CHAR(11) NOT NULL,
	NOME VARCHAR(30) NOT NULL,
	PRIMARY KEY(CPF)
);

CREATE TABLE RESERVA(
	IDRESERVA INT NOT NULL PRIMARY KEY,
	DATAINICIO DATE NOT NULL,
	DATAFIM DATE NOT NULL,
	DATARESERVA DATE NOT NULL,
);

CREATE TABLE ALUGUEL(
	IDALUGUEL INT NOT NULL,
	DATAINICIO DATE NOT NULL,
	DATAFIM DATE NOT NULL,
	VALOR NUMERIC(7,2),
	DIAS INT,
	IDRESERVA INT,
	CPF CHAR(11) NOT NULL,
	PLACA CHAR(7) NOT NULL,
	PRIMARY KEY (IDALUGUEL),
    FOREIGN KEY (IDRESERVA) REFERENCES RESERVA(IDRESERVA),
	FOREIGN KEY (CPF) REFERENCES CLIENTE(CPF),
	FOREIGN KEY (PLACA) REFERENCES AUTOMOVEL (PLACA)
);

