DROP TABLE SUPPLIERS,SUPPLY_PRODUCT,PRODUCTS;
CREATE TABLE SUPPLIERS (
	SUPPLIER VARCHAR,
	NAME VARCHAR,
	STATUS INTEGER,
	CITY VARCHAR
);
CREATE TABLE PRODUCTS (
	PRODUCT VARCHAR,
	NAME VARCHAR,
	COLOR VARCHAR,
	WEIGHT INTEGER,
	CITY VARCHAR	
);
CREATE TABLE SUPPLY_PRODUCT (
	SUPPLIER VARCHAR,
	PRODUCT VARCHAR,
	QUANTITY INTEGER
);
INSERT INTO SUPPLIERS values
	('S1', 'Smith', 20, 'Londres'),
	('S2', 'Jones', 10, 'Paris'),
	('S3', 'Blake', 30, 'Paris'),
	('S4', 'Clark', 20, 'Londres'),
	('S5', 'Adams', 30, 'Atenas');

INSERT INTO SUPPLY_PRODUCT VALUES
	('S1', 'P1', 300),
	('S1', 'P2', 200),
	('S1', 'P3', 400),
	('S1', 'P4', 200),
	('S1', 'P5', 100),
	('S2', 'P1', 300),
	('S2', 'P2', 400),
	('S3', 'P2', 200),
	('S4', 'P4', 300),
	('S4', 'P5', 400);
INSERT INTO PRODUCTS VALUES 
	('P1', 'PORCA', 'VERMELHO', 12, 'LONDRES'),
	('P2', 'TRINCO', 'VERDE', 17, 'PARIS'),
	('P3', 'PARAFUSO', 'AZUL', 17, 'ROMA'),
	('P4', 'PARAFUSO', 'VERMELHO', 14, 'LONDRES'),
	('P5', 'PREGO', 'AZUL', 12, 'PARIS'),
	('P6', 'ROSCA', 'VERMELHO', 19, '');

SELECT CITY, S.SUPPLIER, SUM (QUANTITY) FROM SUPPLIERS AS S 
JOIN SUPPLY_PRODUCT AS SP ON S.SUPPLIER = SP.SUPPLIER 
GROUP BY CITY, S.SUPPLIER;

https://editor.datatables.net/generator/
