DROP TABLE IF EXISTS PROFESSOR,
                      EDICAO,
                      TRABALHO,
                      COMITE,
                      AVALIACAO,
                      SUBMISSAO,
                      AUTORIA,
                      AUTOR;

CREATE TABLE PROFESSOR(
    IDPROFESSOR INT NOT NULL PRIMARY KEY,
    NOME VARCHAR(30) NOT NULL
);

CREATE TABLE EDICAO(
    IDEDICAO INT NOT NULL PRIMARY KEY,
    DESCRICAO VARCHAR(50)
);

CREATE TABLE TRABALHO(
    IDTRABALHO INT NOT NULL PRIMARY KEY,
    TITULO VARCHAR(50) NOT NULL,
    RESUMO VARCHAR(500) NOT NULL,
    AREA VARCHAR(30),
    DOC VARCHAR(100) NOT NULL,
    DOCFINAL VARCHAR(100) NOT NULL,
    CONCEITOFINAL CHAR NOT NULL
 );

 CREATE TABLE AUTOR( 
     IDAUTOR INT NOT NULL PRIMARY KEY,
     NOME VARCHAR(30) NOT NULL, 
     EMAIL VARCHAR(50) NOT NULL
 );

 CREATE TABLE COMITE(
    IDMEMBRO INT NOT NULL PRIMARY KEY,
    IDPROFESSOR INT NOT NULL REFERENCES PROFESSOR(IDPROFESSOR),
    IDEDICAO INT NOT NULL REFERENCES EDICAO(IDEDICAO)
);

CREATE TABLE AVALIACAO(
    IDAVALIACAO INT NOT NULL PRIMARY KEY,
    NOTA FLOAT NOT NULL,
    CONCEITO CHAR NOT NULL,
    IDTRABALHO INT NOT NULL REFERENCES TRABALHO(IDTRABALHO),
    IDMEMBRO INT NOT NULL REFERENCES COMITE(IDMEMBRO)
);

CREATE TABLE AUTORIA( 
    IDTRABALHO INT NOT NULL REFERENCES TRABALHO(IDTRABALHO),
    IDAUTOR INT NOT NULL REFERENCES AUTOR(IDAUTOR)
);

CREATE TABLE SUBMISSAO( 
    IDTRABALHO INT NOT NULL REFERENCES TRABALHO(IDTRABALHO),
    IDEDICAO INT NOT NULL REFERENCES EDICAO(IDEDICAO)
);



