CREATE TABLE PLANOSAUDE(
	IDPLANOSAUDE CHAR(3) NOT NULL,
	SIGLA CHAR(5),
	PRIMARY KEY (IDPLANOSAUDE)
);

CREATE TABLE CONTRATO(
	IDCONTRATO CHAR(9) NOT NULl,
	VIGENCIA NUMERIC (3,2) NOT NULL,
	DATACONTRATO DATE NOT NULL,
	IDPLANOSAUDE CHAR(3) NOT NULL,
	PRIMARY KEY (IDCONTRATO),
	FOREIGN KEY (IDPLANOSAUDE) REFERENCES PLANOSAUDE(IDPLANOSAUDE));
	
CREATE TABLE CLIENTE (
	CPF INT NOT NULL,
	NOME VARCHAR(30) NOT NULL,
	ENDERECO VARCHAR (50) NOT NULL,
	PRIMARY KEY (CPF));
	
CREATE TABLE CREDENCIADO(
	CNPJ INT NOT NULL,
	NOME VARCHAR(30) NOT NULL,
	PRIMARY KEY (CNPJ));
	
CREATE TABLE PROCEDIMENTO (
	IDPROCEDIMENTO INT NOT NULL,
	DESCRICAO VARCHAR(30) NOT NULL,
	PRIMARY KEY (IDPROCEDIMENTO));

CREATE TABLE PARTICIPACAO (
	IDPARTICIPACAO INT NOT NULL,
	DESCRICAO VARCHAR(30) NOT NULL,
	TIPOPAPEL PAPEL NOT NULL,
	CPF INT NOT NULL,
	IDCONTRATO CHAR(9) NOT NULL,
	PRIMARY KEY (IDPARTICIPACAO),
	FOREIGN KEY (IDCONTRATO) REFERENCES CONTRATO(IDCONTRATO),
	FOREIGN KEY (CPF) REFERENCES CLIENTE(CPF));

CREATE TABLE COBRANCA (
	IDPARTICIPACAO INT NOT NULL,
	CNPJ INT NOT NULL,
	IDPROCEDIMENTO INT NOT NULL,
	DATACOBRANCA DATE NOT NULL,
	QUANTIDADE INT NOT NULL,
	PRIMARY KEY(IDPARTICIPACAO, CNPJ, IDPROCEDIMENTO),
	FOREIGN KEY (IDPARTICIPACAO) REFERENCES PARTICIPACAO (IDPARTICIPACAO),
	FOREIGN KEY (CNPJ) REFERENCES CREDENCIADO (CNPJ),
	FOREIGN KEY (IDPROCEDIMENTO) REFERENCES PROCEDIMENTO(IDPROCEDIMENTO));

CREATE TABLE COBERTURA(
	IDPLANOSAUDE CHAR(3) NOT NULL,
	IDPROCEDIMENTO INT NOT NULL,
	QUANTIDADE INT NOT NULL,
	PRIMARY KEY(IDPLANOSAUDE, IDPROCEDIMENTO),
	FOREIGN KEY (IDPLANOSAUDE) REFERENCES PLANOSAUDE(IDPLANOSAUDE),
	FOREIGN KEY (IDPROCEDIMENTO) REFERENCES PROCEDIMENTO (IDPROCEDIMENTO));