/*Aluno (matricula, sobrenome, nome, email)
Disiplina (codigo, nome)
Turma (codigo, disciplina, semestre, professor)
Inscricao (turma, aluno, nota)*/
DROP TABLE IF EXISTS ALUNO, DISCIPLINA, TURMA, INSCRICAO;

CREATE TABLE ALUNO(
	MATRICULA CHAR(5) NOT NULL PRIMARY KEY,
	NOME VARCHAR(30) NOT NULL,
	SOBRENOME VARCHAR(30) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL
);

CREATE TABLE DISCIPLINA(
	CODDISCIPLINA INT NOT NULL PRIMARY KEY,
	NOME VARCHAR(30)
);
CREATE TABLE TURMA(
	CODTURMA INT NOT NULL PRIMARY KEY,
	SEMESTRE CHAR(6),
	PROFESSOR VARCHAR(30) NOT NULL,
	CODDISCIPLINA INT NOT NULL REFERENCES DISCIPLINA(CODDISCIPLINA)
);	

CREATE TABLE INSCRICAO (
	CODTURMA INT NOT NULL REFERENCES TURMA(CODTURMA),
	MATRICULA CHAR(5) NOT NULL REFERENCES ALUNO(MATRICULA),
	NOTA FLOAT NOT NULL
);
INSERT INTO DISCIPLINA VALUES (1,'BD I');
SELECT * FROM DISCIPLINA;
INSERT INTO TURMA (CODTURMA, SEMESTRE, PROFESSOR, CODDISCIPLINA)
    VALUES (1, '2020.1', 'LUIS PAES LEME', 1);
SELECT * FROM TURMA;
INSERT INTO ALUNO VALUES
('AAAAA', 'TIAGO', 'MATOS', 'NOME@FACULDADE'),
('AAAAB', 'GABRIEL', 'MOREIRA', 'NOME@FACULDADE'),
('AAAAC',  'BRUNO' ,  'RODRIGUES' ,  'NOME@FACULDADE' ),
('AAAAD' ,  'RENAN' ,  'LIMEIRA' ,  'NOME@FACULDADE');
SELECT * FROM ALUNO;
INSERT INTO INSCRICAO VALUES
	(1,'AAAAA',7),
	(1,'AAAAB',10),
	(1,'AAAAC',10),
	(1,'AAAAD',7),
	(1,'AAAAC',8),
	(1,'AAAAA',8),
	(1,'AAAAB',7),
	(1,'AAAAC',10),
	(1,'AAAAD',10),
	(1,'AAAAA',7),
	(1,'AAAAB',7),
	(1,'AAAAC',10),
	(1,'AAAAD',10),
	(1,'AAAAA',8),
	(1,'AAAAB',7),
	(1,'AAAAC',8);
SELECT * FROM INSCRICAO;
SELECT COUNT(DISTINCT INSCRICAO.MATRICULA) FROM  INSCRICAO 
JOIN TURMA ON (INSCRICAO.CODTURMA = TURMA.CODTURMA) 
JOIN DISCIPLINA ON (TURMA.CODDISCIPLINA = DISCIPLINA.CODDISCIPLINA)
WHERE DISCIPLINA.NOME = 'BD I';


SELECT ALUNO.MATRICULA, ALUNO.NOME FROM INSCRICAO 
JOIN ALUNO ON INSCRICAO.MATRICULA= ALUNO.MATRICULA 
WHERE NOTA = 10
GROUP BY ALUNO.NOME, ALUNO.MATRICULA
HAVING COUNT(*) >= 2;

SELECT ALUNO.MATRICULA, ALUNO.NOME FROM INSCRICAO 
JOIN ALUNO ON INSCRICAO.MATRICULA= ALUNO.MATRICULA 
WHERE NOTA = 10
GROUP BY ALUNO.NOME, ALUNO.MATRICULA
HAVING COUNT(*) = 2;